### ISSUE TITLE
Question about allOf

### ISSUE THREAD

**Issue by coodoo** [danidiaz/lens-aeson-examples#1]
Was wondering should the result by using `allOf` be just `["Jim"]` for that `Bob` has no pets at all?

https://github.com/danidiaz/lens-aeson-examples/blob/e364e96ac2ef6737b93f7d06e94622b5c1aef034/src/Data/Aeson/Lens/Examples.hs#L189

**Comment by danidiaz** [comment]
In [logic](https://math.stackexchange.com/questions/202452/why-is-predicate-all-as-in-allset-true-if-the-set-is-empty), these kinds of "every element satisfies predicate X" statements are true over empty sets. Think of them as saying "there is not an element that doesn't satisfy predicate X", which of course it's true for the empty set because there are no elements!

But now I wonder how to best express "Getting the names of all persons who have at least one pet and whose every pet is a dog".

**Comment by coodoo** [comment]
Haha, seems I need to do some catch up on the math side of things, this is so fun that for following example, it's like saying `All of my children are rock stars, if I ever had any`😆

```
"All of my children are rock stars."

"If we go through the list of my children, one at a time, you will never find one that is not a rock star."
```

**Comment by danidiaz** [comment]
Added new example "Getting the names of all persons with at least one pet whose every pet is a dog".

**Comment by coodoo** [comment]
Could this new example used to grab everyone with a dog that's over age of 45? Meaning filtering with multiple criteria?

**Comment by danidiaz** [comment]
Yes.
